### ISSUE TITLE
Minimax algorithm with alpha-beta prunning

### ISSUE THREAD

**Issue by michalnowak061** [TheAlgorithms/Swift#23]
Brief Intro

Hi there 👋🏻

I would like to add an implementation and an example of using the minimax algorithm. It's an algorithm used in games for example in Tic Tac Toe, and many other games in which we are able to assess the state of the game.

Do you think it will be useful?

More Details

More about algorithm: https://en.wikipedia.org/wiki/Minimax
More about alpha-beta prunning: https://en.wikipedia.org/wiki/Alpha–beta_pruning

**Comment by TiagoMaiaL** [comment]
Hello, @michalnowak061.

I'm not a maintainer of the repository, but I believe this would be a good addition, since this repository is a compilation of different algorithms implemented for learning purposes.

**Comment by TiagoMaiaL** [comment]
I think we can close this issue, as the work for it was already merged.
