### ISSUE TITLE
Implementation of Merge Sort

### ISSUE THREAD

**Issue by GervinFung** [TheAlgorithms/Swift#25]
Good evening Sir, I would like to the following sorting algorithm into this repository

- Merge Sort

Do you think it will be useful? I think it will be helpful to have Merge Sort algorithm added as it's one of the most efficient and stable sorting algorithm. Thank you for your time and consideration, I look forward to hearing from you

**Comment by TiagoMaiaL** [comment]
Good evening, @GervinFung. There's an open MR with an implementation for merge sort: https://github.com/TheAlgorithms/Swift/pull/24

However, there are a lot of algorithms that can be added in this repository. You can check the python repository in this organization, it contains a lot of algorithms that could be added here as well.

**Comment by GervinFung** [comment]
Hi @TiagoMaiaL, thank you for your reply, since Merge Sort is done by the other, could I do `Counting Sort` or `Exchange Sort` as I think the 2 sorting algorithms mentioned is beginner-friendly

**Comment by TiagoMaiaL** [comment]
Nice! I can help by reviewing these MRs.

**Comment by TiagoMaiaL** [comment]
We can close this issue as the work was merged.
