### ISSUE TITLE
Implement DFS and BFS

### ISSUE THREAD

**Issue by zohairhadi** [TheAlgorithms/Swift#39]
These simple algorithms are not yet implemented in this repo. Would be useful if we can have these. And I would love to add them!

**Comment by Minkyeong-Ko** [comment]
Hi can I be assigned to this?

**Comment by zohairhadi** [comment]
How bout we split the work xd. I forgot this issue was open.
You can work on DFS and I can do BFS

**Comment by Minkyeong-Ko** [comment]
Okay I'll work on DFS

**Comment by Minkyeong-Ko** [comment]
Hi @zohairhadi I'll cancel this issue! I thought you were the owner of the repository😂

**Comment by zohairhadi** [comment]
lol, I wish. You can create a new PR for just DFS
